services:
  api:
    image: webdevops/php-nginx-dev:8.3
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "9000:80"
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_DOCUMENT_INDEX=index.php
    restart: unless-stopped
    
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: track_app
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password

  ui:
    image: node:22
    container_name: ui
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "9001:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

volumes:
  db_data:

networks:
  default:
    